name:                cranberry
version:             0.1.0.0
github:              "cheeze2000/cranberry"
license:             BSD3
author:              "Nicholas"
maintainer:          "me@cheeze2000.net"
copyright:           "2020 Nicholas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cheeze2000#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- casing
- req
- text
- unordered-containers
- websockets
- wuss

library:
  source-dirs: src

executables:
  cranberry-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cranberry